# Generated by Django 4.2 on 2023-06-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='purchaser',
            new_name='pur2',
        ),
    ]
